### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by freshmenyuan** [JavaScriptAcademy/meteor-adam#1]
- [ ] Login/Signup #2
- [ ] Game panel  #3
  - [ ] game interface #4
    - [ ] create and list game rooms #9
  - [ ] game logic #5
  - [ ] Pie chart show live results  #8
- [ ] Show player records (info) #6 
- [ ] World ranking list #7
